// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\" data-theme=\"nord\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"https://unpkg.com/htmx.org@2.0.3\"></script><link href=\"https://cdn.jsdelivr.net/npm/daisyui@4.12.14/dist/full.min.css\" rel=\"stylesheet\" type=\"text/css\"><script src=\"https://cdn.tailwindcss.com\"></script><title>Reminder</title><!-- Add your custom styles for the overlay --><style>\n\t\t\t\t/* Ensure the overlay covers the entire viewport */\n\t\t\t\t#overlay {\n\t\t\t\t\tdisplay: none; /* Hidden by default */\n\t\t\t\t\tposition: fixed;\n\t\t\t\t\ttop: 0;\n\t\t\t\t\tleft: 0;\n\t\t\t\t\tright: 0;\n\t\t\t\t\tbottom: 0;\n\t\t\t\t\tbackground-color: rgba(0, 0, 0, 0.5); /* Semi-transparent dark background */\n\t\t\t\t\tbackdrop-filter: blur(5px); /* Applies blur effect to the background */\n\t\t\t\t\tz-index: 9999; /* Makes sure it is above other content */\n\t\t\t\t}\n\t\t\t\t#overlay .loading-text {\n\t\t\t\t\tfont-size: 24px;\n\t\t\t\t\tcolor: white;\n\t\t\t\t}\n\t\t\t</style></head><body><!-- Full-Screen Overlay (Initially hidden) --><div id=\"overlay\" class=\"hidden\"><div class=\"w-full h-full flex justify-center items-center\"><div class=\"text-white text-xl\">Loading...</div></div></div><main class=\"container mx-auto mt-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</main><script>\n\t\t\t\t// Show overlay before the request is made\n\t\t\t\tdocument.body.addEventListener('htmx:configRequest', function () {\n\t\t\t\t\tdocument.getElementById('overlay').classList.remove('hidden');\n\t\t\t\t});\n\n\t\t\t\t// Hide overlay after the request is finished\n\t\t\t\tdocument.body.addEventListener('htmx:afterSwap', function () {\n\t\t\t\t\tdocument.getElementById('overlay').classList.add('hidden');\n\t\t\t\t});\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
