// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
	"time"
)

type Notification struct {
	ID          int64
	ReminderID  int64
	DueDate     time.Time
	DismissedAt sql.NullTime
}

type Reminder struct {
	ID        int64
	Title     string
	CreatedAt time.Time
}
